from __future__ import annotations

import os
from pathlib import Path


DEFAULT_DATA_DIR = Path(os.environ.get("BALL_TRACKER_DATA_DIR", "data"))
DEVICE_STALE_S = 3.0
DEVICE_GC_AFTER_S = 60.0
DEVICE_REGISTRY_CAP = 64
DISARM_ECHO_S = 5.0
SYNC_TIMEOUT_S = 8.0
SYNC_COOLDOWN_S = 10.0
SYNC_COMMAND_TTL_S = 10.0
TIME_SYNC_INTENT_WINDOW_S = 20.0
TIME_SYNC_MAX_AGE_S = 30.0
MAX_PITCH_UPLOAD_BYTES = 500 * 1024 * 1024
CALIBRATION_FRAME_TTL_S = 10.0
